# Generated by Django 6.0 on 2025-12-09 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='owner',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='device',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='device',
            name='description',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='temperature',
        ),
        migrations.AddField(
            model_name='device',
            name='is_armed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='sensor_type',
            field=models.CharField(default='motion', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensordata',
            name='unit',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='value',
            field=models.CharField(default='motion', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(default='My Security System', max_length=100),
        ),
    ]
